# Generated by Django 5.0 on 2023-12-19 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_date', models.DateField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('discarded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.log')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.paper')),
            ],
        ),
        migrations.CreateModel(
            name='CostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.log')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('delivery', models.BooleanField()),
                ('cost', models.FloatField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.paper')),
            ],
        ),
        migrations.CreateModel(
            name='UndeliveredDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.paper')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deliverylog',
            constraint=models.UniqueConstraint(fields=('log', 'paper', 'date'), name='unique_delivery_log'),
        ),
        migrations.AddConstraint(
            model_name='costlog',
            constraint=models.UniqueConstraint(fields=('log', 'paper'), name='unique_cost_log'),
        ),
        migrations.AddConstraint(
            model_name='cost',
            constraint=models.UniqueConstraint(fields=('paper', 'day'), name='unique_day'),
        ),
        migrations.AddConstraint(
            model_name='cost',
            constraint=models.UniqueConstraint(fields=('paper', 'delivery'), name='unique_cost'),
        ),
        migrations.AddConstraint(
            model_name='undelivereddates',
            constraint=models.UniqueConstraint(fields=('paper', 'date'), name='unique_undelivered_dates'),
        ),
    ]
