# Generated by Django 5.0 on 2023-12-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cost',
            name='unique_cost',
        ),
    ]
